# Generated by Django 5.2.15 on 2026-06-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('format', models.CharField(choices=[('SINGLE_ROUND_ROBIN', 'Single Round Robin'), ('DOUBLE_ROUND_ROBIN', 'Double Round Robin')], default='SINGLE_ROUND_ROBIN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
